### ISSUE TITLE
Active: active (running) Issue 

### ISSUE THREAD

**Issue by Phoenix-999** [SasukeFreestyle/Hysteria2-Iran#1] opened 2023-09-19 14:02 UTC
Hi @SasukeFreestyle,
Thank you for the clear guidelines on setting up Hysteria2-Iran. 
I followed all your instructions step by step. However, when I launched Sing-box and checked if it was running or not, I received this message:  `Active: activating (auto-restart)`

![Screenshot 2023-09-19 at 14 52 17](https://github.com/SasukeFreestyle/Hysteria2-Iran/assets/127796122/1744eb28-2b55-4b77-9fc8-01fbc881e644)

- My username is root
- The VPS server is fresh 
- The IP address is clean

Could you please assist me in resolving this issue?
Thank you in advance

**Comment by SasukeFreestyle** [comment] 2023-09-19 14:22
I think maybe something wrong in the config.json file

could you cd into hy2 directory and run
```
./sing-box run -c config.json
```
Do you get any errors?

Also show me your hy2.service file.

**Comment by SasukeFreestyle** [comment] 2023-09-19 16:23
Everything looks fine 🤔 paths looks correct e.t.c

Im trying to reproduce the error but I'm unable to.

Also i updated my hy2.service file. It was missing some parts.

What happens if you do 
```
sudo ./sing-box run -c config.json
```
?

**Comment by SasukeFreestyle** [comment] 2023-09-19 16:55
I just followed my guide again and I'm still unable to reproduce.

![1](https://github.com/SasukeFreestyle/Hysteria2-Iran/assets/2391403/a41d772c-0287-48c4-9406-8cbde90fdff0)
![2](https://github.com/SasukeFreestyle/Hysteria2-Iran/assets/2391403/998103e8-aa6b-41d0-9006-03d5d4a100d9)
![3](https://github.com/SasukeFreestyle/Hysteria2-Iran/assets/2391403/0623f068-9611-4b81-bd3b-6d203e30b7ab)
![4](https://github.com/SasukeFreestyle/Hysteria2-Iran/assets/2391403/d597559f-65de-4e15-94df-de630f7f2e3b)


what does this command say?
```
sudo lscpu | grep Architecture
```
![bild](https://github.com/SasukeFreestyle/Hysteria2-Iran/assets/2391403/5e1e96d3-a562-4f38-a30a-98a457496444)

**Comment by SasukeFreestyle** [comment] 2023-09-19 17:19
Thank you again for your kind words.

I will look into this, I honestly have no idea why this error occurs for you.

Leaving issue open until you or someone else find a solution.

**Comment by SasukeFreestyle** [comment] 2023-09-24 08:59
I'm glad you got it working.

I've not tried running sing-box as root user as I prefer not to run any programs as root unless its necessary.

I will try to run it as root myself later (busy today) if root does not work for me I will update the guide with a notice that it does not work with root user.

Closing this issue as it is resolved.

**Closed by SasukeFreestyle** 2023-09-24 08:59 UTC
